{% set name = "xbcausalforest" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xbcausalforest-{{ version }}.tar.gz
  sha256: fbc0f7fc87028ba72bab7de6db2563e34e8501239a18997d4b3babdb066b8969

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - xbcausalforest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xbcausalforest/
  summary: Implementation of Accelerated Bayesian Causal Forests
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - MatthiasLuxQC
